# Generated by Django 4.0.3 on 2022-03-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_measurment_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
